### ISSUE TITLE
Take a look at composer-merge-plugin

### ISSUE THREAD

**Issue by bethrezen** [DevGroup-ru/yii2-extensions-manager#5]
[Composer merge plugin](https://github.com/wikimedia/composer-merge-plugin) allows merging dependencies of external composer.json to base project's composer.json :)

If it works well we can require plugins into _local_ composer.json file and keep core dp3 composer.json clean and updatable(via git pull for example).

Requiring into _local_ composer.json file should be added as module configurable option: [composer working dir](https://getcomposer.org/doc/03-cli.md#global-options) or [COMPOSER env variable](https://getcomposer.org/doc/03-cli.md#composer)).

> :information_source: **Tip:** composer merge plugin allows using of patterns, ie.:
> 
> ``` json
>     "extra": {
>         "merge-plugin": {
>             "include": [
>                 "plugins/*/*/composer.json"
>             ],
>             "recurse": false,
>             "replace": false,
>             "merge-extra": true
>         }
>     }
> ```

**/cc** @iVovolk @fps01 @Philosoft @ivansal plz discuss or vote for this feature :grey_exclamation:

**Comment by Hector68** [comment]
Maybe use Project theme as local composer pachege with own dependencies. Sample:

```
{
    "repositories": [
        {
            "type": "path",
            "url": "../../themes/my-project"
        }
    ],
    "require": {
        "themes/my-project": "*"
    }
}
```

**Comment by bethrezen** [comment]
pachege? Whyyyyy? :-D
Ok, that's just an example of package but it does not make sense.
The killer feature of this package is that your main `composer.json` can be in repository and your local plugins/themes/anything can be in local file `composer-local.json` where all dependencies are stored.
`composer-local.json` is not stored in any repository and exists only in working copy.
Therefore, you can add anything you want there including custom external repositories. The only thing you should care of is correct merging and processing extensions in manager.

**Comment by fps01** [comment]
It's a good idea without many words.
Just need to test it.

**Comment by iVovolk** [comment]
Ok. This can be helpful. How do i see this:
1. we have "extensions" folder in DotPlan core
2. we store there composer.json with only "required" section and "config" section, where `"vendor-dir" : "../vendor",`
3. all of these files are gitignored. composer.json will be auto generated while extensions-manager first time runs
4. all our work with current instance extensions will be done in this folder and with this composer.json
5. in root applications composer.json we add
`"wikimedia/composer-merge-plugin": "^1.3"` in "required"
and 

```
"merge-plugin": {
      "include": [
        "extensions/composer.json"
      ]
    }
```

in extra
6. This way our application root composer.json will be clean and beauty and all local extensions will be gitignored

If that's ok, i'll do it this way

**Comment by iVovolk** [comment]
Done
